### PR TITLE
pass jqXHR object to logger

### PR DESCRIPTION
**Pull request by fidelscodes**
This changeset simply adds the ability to pass the jqXHR response through to `visitor.logError()`. This will give us access to things like status and responseText directly in the consuming application. This way we can filter out errors based on status.

### CODE REVIEW

**Comment by fidelscodes** [comment]
/domain @joejansen @chrislopresto @LucasSantoro @rnackman @samandmoore 
/platform @aburgel @samandmoore @chrislopresto

**Comment by fidelscodes** [comment]
bump nanda?

**Comment by fidelscodes** [comment]
not entirely sure where that failure on Travis CI comes from...

**Comment by fidelscodes** [comment]
bump nanda?

**Comment by fidelscodes** [comment]
bump nanda?

**Comment by rnackman** [comment]
<<domain lgtm

**Comment by fidelscodes** [comment]
bump @chrislopresto

**Comment by fidelscodes** [comment]
Recap of discussion with Chris:

We will punt on this for now and try to implement the hack where we need it. Since this is OSS, we don't want to mess around with the API if we can avoid it.

**Pull request closed without merging**
