### PR TITLE
Bump version to 2.0.0

### PR DESCRIPTION
**Pull request by aburgel**
/domain @Betterment/test_track_core 
/no-platform

Officially calling this 2.0!

### CODE REVIEW

**Comment by HipsterBrown** [comment]
<< domainLGTM

**Comment by smudge** [comment]
<< domain LGTM - but we may want to merge the other dependabot PR first!

**Comment by HipsterBrown** [comment]
Any release notes we want to follow up with here? Either in the github release or a CHANGELOG.md?

**Comment by aburgel** [comment]
Will add some notes to the github release once it's up.

**Pull request merged**
